# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

add_configuration_score_to_db <- function(str_key, value, mInfo) {
    invisible(.Call('l1ou_add_configuration_score_to_db', PACKAGE = 'l1ou', str_key, value, mInfo))
}

get_stored_config_score <- function() {
    .Call('l1ou_get_stored_config_score', PACKAGE = 'l1ou')
}

erase_configuration_score_db <- function() {
    invisible(.Call('l1ou_erase_configuration_score_db', PACKAGE = 'l1ou'))
}

get_score_of_configuration <- function(str_key) {
    .Call('l1ou_get_score_of_configuration', PACKAGE = 'l1ou', str_key)
}

cmp_sqrt_OU_covariance <- function(edgeList, nTips) {
    .Call('l1ou_cmp_sqrt_OU_covariance', PACKAGE = 'l1ou', edgeList, nTips)
}

