# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

add_placement_score_to_db <- function(str_key, value) {
    invisible(.Call('l1ou_add_placement_score_to_db', PACKAGE = 'l1ou', str_key, value))
}

erase_placement_score_db <- function() {
    invisible(.Call('l1ou_erase_placement_score_db', PACKAGE = 'l1ou'))
}

get_score_of_placement <- function(str_key) {
    .Call('l1ou_get_score_of_placement', PACKAGE = 'l1ou', str_key)
}

